### ISSUE TITLE
Ioncube Decoder

### ISSUE THREAD

**Issue by ghost** [0x241/h-script-4#1]
I have encrypted php file. encrypted with ioncube 11. I follow you on github. I found out that it decrypts encrypted files.
WiseCP software like Whmcs needs to be decrypted.
https://drive.google.com/file/d/1MPbJhw7ljxt5IeNrGshXNxGi8tjTZsU5/
Can you help me?

**Comment by 0x241** [comment]
Hi, try to find easytoyou service on google but if the file is additionally obfuscated then it will not help :)
